; NOTE: no string should have quotes

[host.tools]
; the relative path to bflat, the C# low-level compiler; set to "bflat" if the tool is installed globally
;  and can be called from anywhere
bflat_compiler = tools/bflat-10.0.0-rc.1/bflat

[host.vm_testing]
vm_img_file = run/chihuahua_os.img