<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$(CustomSdkDir)ChihuahuaOS.CustomCoreLib.props" />
    <Import Project="Kernel.BuildOverride.targets" />
    <Import Project="Kernel.Installer.targets" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Configurations>Debug;Release</Configurations>
        <EntryPointSymbol>_start</EntryPointSymbol>
        <Platforms>AnyCPU</Platforms>
        <Version>0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../StaticLibs/CoreLib/ChihuahuaOS.CoreLib/ChihuahuaOS.CoreLib.csproj" />
        <ProjectReference Include="../ChihuahuaOS.InitRd/ChihuahuaOS.InitRd.csproj" />

        <ProjectReference Include="../../Boot/ChihuahuaOS.EfiApi/ChihuahuaOS.EfiApi.csproj" />
        <ProjectReference Include="../../Boot/ChihuahuaOS.BootParams/ChihuahuaOS.BootParams.csproj" />

        <ProjectReference Include="../../StaticLibs/ChihuahuaOS.MemPaginator/ChihuahuaOS.MemPaginator.csproj" />
        <ProjectReference Include="../../StaticLibs/ChihuahuaOS.MinimalUtils/ChihuahuaOS.MinimalUtils.csproj" />
        <ProjectReference Include="../../StaticLibs/CoreLib/ChihuahuaOS.CoreLib.Kernel/ChihuahuaOS.CoreLib.Kernel.csproj" />
        <ProjectReference Include="../../StaticLibs/FileSystems/ChihuahuaOS.Fs.Ustar/ChihuahuaOS.Fs.Ustar.csproj" />
        <ProjectReference Include="../ChihuahuaOS.Kernel.MemoryManager/ChihuahuaOS.Kernel.MemoryManager.csproj" />
    </ItemGroup>

</Project>
