<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$(CustomSdkDir)ChihuahuaOS.CustomCoreLib.props" />

    <PropertyGroup>
        <RootNamespace>""</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../ChihuahuaOS.CoreLib/ChihuahuaOS.CoreLib.csproj" />
    </ItemGroup>
</Project>
