namespace System.Runtime.CompilerServices;

/// <summary>
/// Contains generic, low-level functionality for manipulating pointers.
/// </summary>
public static unsafe class Unsafe
{
    //NOTE: this should be automatically generated by the compiler. .NET runtime only implements them if !CORECLR

    /// <summary>
    /// Returns a pointer to the given by-ref parameter.
    /// </summary>
    [Intrinsic]
    public static extern void* AsPointer<T>(ref T value);

    /// <summary>
    /// Adds an element offset to the given reference.
    /// </summary>
    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern ref T Add<T>(ref T source, int elementOffset);

    /// <summary>
    /// Adds an element offset to the given reference.
    /// </summary>
    [Intrinsic]
    public static extern ref T Add<T>(ref T source, nint elementOffset);

    /// <summary>
    /// Reinterprets the given reference as a reference to a value of type <typeparamref name="TTo"/>.
    /// </summary>
    /// <typeparam name="TFrom">The source type of the reference to reinterpret.</typeparam>
    /// <typeparam name="TTo">The destination type to reinterpret the reference as.</typeparam>
    [Intrinsic]
    public static extern ref TTo As<TFrom, TTo>(ref TFrom source);

    /// <summary>
    /// Casts the given object to the specified type, performs no dynamic type checking.
    /// </summary>
    [Intrinsic]
    public static extern T As<T>(object? o) where T : class;

    /// <summary>
    /// Reinterprets the given location as a reference to a value of type <typeparamref name="T"/>.
    /// </summary>
    [Intrinsic]
    public static extern ref T AsRef<T>(void* source);

    /// <summary>
    /// Determines the byte offset from origin to target from the given references.
    /// </summary>
    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern IntPtr ByteOffset<T>(ref readonly T origin, ref readonly T target);

    /// <summary>
    /// Subtracts an element offset from the given reference.
    /// </summary>
    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern ref T Subtract<T>(ref T source, int elementOffset);

    /// <summary>
    /// Subtracts an element offset from the given void pointer.
    /// </summary>
    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern void* Subtract<T>(void* source, int elementOffset);

    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern TTo BitCast<TFrom, TTo>(TFrom source)
        where TFrom : allows ref struct
        where TTo : allows ref struct;

    [Intrinsic]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static extern ref T AddByteOffset<T>(ref T source, nuint byteOffset)
        where T : allows ref struct;
}