<Project>
    
    <Import Project="ChihuahuaOS.BuildConfig.props" />
    
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RuntimeMetadataVersion>v4.0.30319</RuntimeMetadataVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <NoStdLib>true</NoStdLib>
        <NoConfig>true</NoConfig>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>

        <!-- Prevent the compiler for searching the toolchain for UEFI/ChihuahuaOS (there is none) -->
        <SelfContained>false</SelfContained>
        <UseAppHost>false</UseAppHost>
        <DisableTransitiveFrameworkReferenceDownloads>true</DisableTransitiveFrameworkReferenceDownloads>
    </PropertyGroup>
    
    <ItemGroup>
        <IntemediateFilesGlob Include="*.o" />
        <IntemediateFilesGlob Include="*.pdb" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'DebugUefi' or '$(Configuration)' == 'Debug'">
        <Optimize>false</Optimize>
        <DebugSymbols>true</DebugSymbols>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'ReleaseUefi' or '$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
        <DebugSymbols>false</DebugSymbols>
        <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    </PropertyGroup>

    <!-- TODO: add here architecture-specific conditions and properties -->
    <PropertyGroup>
        <PlatformTarget>x64</PlatformTarget>
        <ArchName>X64</ArchName>
        <DefineConstants>$(DefineConstants);ARCH_X64</DefineConstants>
    </PropertyGroup>
    
    <Import Project="ChihuahuaOS.Uefi.props" />
    <Import Project="ChihuahuaOS.LowOS.props" />

    <Import Project="ChihuahuaOS.CustomCoreLib.targets" />
    <Import Project="ChihuahuaOS.Uefi.targets"/>
    <Import Project="ChihuahuaOS.LowOS.targets" />
    
</Project>